# Generated by Django 6.1.1 on 2026-09-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=120)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('hybrid', 'Гибрид'), ('offline', 'Очно')], default='online', max_length=10)),
                ('format_note', models.CharField(blank=True, max_length=80)),
                ('document', models.CharField(blank=True, max_length=60)),
                ('price', models.CharField(blank=True, max_length=60)),
                ('installment', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('details_url', models.URLField(blank=True)),
                ('school_url', models.URLField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('seo_text', models.TextField(blank=True, verbose_name='SEO-текст (HTML)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='refy.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='refy.section')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='refy.section'),
        ),
    ]
