# Generated by Django 6.1.1 on 2026-10-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('seo_text', models.TextField(blank=True, verbose_name='SEO-текст (HTML)')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Главный раздел',
                'verbose_name_plural': 'Главные разделы',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.FileField(blank=True, upload_to='refy/icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='audience',
            field=models.CharField(blank=True, max_length=120, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='details_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на детали'),
        ),
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.CharField(blank=True, max_length=60, verbose_name='Выдаваемый Документ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_months',
            field=models.PositiveSmallIntegerField(verbose_name='Продолжительность (месяцы)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('hybrid', 'Гибрид'), ('offline', 'Очно')], default='online', max_length=10, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='course',
            name='format_note',
            field=models.CharField(blank=True, max_length=80, verbose_name='Примечание к формату'),
        ),
        migrations.AlterField(
            model_name='course',
            name='installment',
            field=models.BooleanField(default=False, verbose_name='Рассрочка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='course',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=60, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='course',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.CharField(max_length=120, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на школу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=60, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='refy.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='refy.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='refy.section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=120, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='refy.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='refy.category', verbose_name='Главный раздел'),
        ),
    ]
