# Generated by Django 6.1.1 on 2026-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0002_category_section_icon_alter_course_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Продолжительность (дни)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Продолжительность (месяцы)'),
        ),
    ]
