# Generated by Django 6.1.1 on 2026-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0003_course_duration_days_alter_course_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('webinar', 'Вебинар'), ('hybrid', 'Гибрид (онлайн + вебинар)')], default='online', max_length=10, verbose_name='Формат'),
        ),
    ]
