# Generated by Django 6.1.1 on 2026-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0004_alter_course_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school_url',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Адрес страницы'),
        ),
    ]
