# Generated by Django 6.1.1 on 2026-10-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0005_remove_course_school_url_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Адрес страницы')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SchoolReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='refy.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Отзыв о школе',
                'verbose_name_plural': 'Отзывы о школах',
            },
        ),
    ]
