# Generated by Django 6.1.1 on 2026-10-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0006_school_schoolreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reviews_count',
        ),
    ]
