# Generated by Django 6.1.1 on 2026-10-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0007_remove_course_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/', verbose_name='Иконка'),
        ),
    ]
