# Generated by Django 6.1.1 on 2026-10-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0008_alter_section_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, upload_to='refy/courses/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.FileField(blank=True, upload_to='refy/icons/', verbose_name='Иконка'),
        ),
    ]
