# Generated by Django 6.1.1 on 2026-10-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0009_course_image_alter_section_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Страница')),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_bot', models.BooleanField(default=False, verbose_name='Бот')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='refy.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'created_at'], name='refy_clicke_course__b0c092_idx')],
            },
        ),
    ]
