# Generated by Django 6.1.1 on 2026-10-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refy', '0010_clickevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название (для админки)')),
                ('html', models.TextField(blank=True, help_text='HTML и CSS работают. <script> из админки не сработает — JS только в slider.js.', verbose_name='HTML + CSS')),
                ('image', models.FileField(blank=True, help_text='Рекомендуется 1920×720. На мобильных обрезается по центру.', upload_to='refy/slider/', verbose_name='Картинка')),
                ('alt', models.CharField(blank=True, max_length=160, verbose_name='Alt картинки')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка (кнопка)')),
                ('link_text', models.CharField(blank=True, max_length=60, verbose_name='Текст кнопки')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Слайд (hero)',
                'verbose_name_plural': 'Слайды (hero)',
                'ordering': ['position', 'id'],
            },
        ),
    ]
